### ISSUE TITLE
app crashed while running in dev mode 

### ISSUE THREAD

**Issue by prashantsrivastav** [localnerve/flux-react-example-sw#44]
```
flux-react-example-sw/node_modules/fluxible-router/lib/createNavLinkComponent.js:26
        var NavLink = React.createClass(Object.assign({}, {
                                               ^
    TypeError: undefined is not a function
        at createNavLinkComponent (flux-react-example-sw/node_modules/fluxible-router/lib/createNavLinkComponent.js:26:44)
        at Object.<anonymous> (flux-react-example-sw/node_modules/fluxible-router/lib/NavLink.js:10:18)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (flux-react-example-sw/node_modules/fluxible-router/index.js:13:14)
        at Module._compile (module.js:460:26)
    Sat, 05 Dec 2015 06:06:06 GMT nodemon bus emit: log
```

**Comment by localnerve** [comment]
What execution environment is this happening in?
  * Server or client (or while running tests)?

Object.assign requires a polyfill for older JS environments, so please indicate which version of browser or node you are running.

For the client, this should be loaded and run in the client entry via the polyfill. I'm very interested if this is not running as intended, so please let me know about this further.

Thanks for the issue.

**Comment by localnerve** [comment]
This is not reproducible using the correct JS environments.
Haven't heard back from you on this, so I'm closing this issue. If you need help with this, please re-open.
